### ISSUE TITLE
ebook reader needs to be added to the `buid-test-check` workflow

### ISSUE THREAD

**Issue by CesarValiente** [microsoft/surface-duo-window-manager-samples#9]
@raymondliu2022  can you please add ebook-reader project to the existent `build-text-check` workflow? so tests and checks are done also on it?
https://github.com/microsoft/surface-duo-window-manager-samples/blob/c9d47df61282384420ee33716e34139fcae20356/.github/workflows/build_test_check.yml#L24

Thanks!

**Comment by raymondliu2022** [comment]
@CesarValiente I made a PR to merge the changes in - hope I've done it right!
